title: Wei Zhang's Online CV
baseurl: "/OnlineCV/"
color: blue
exclude:
  - README.md
  - "README_zh-CN.md"
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - jekyll-crisp-minimal-resume.gemspec
  - /script
  - /screenshots
  - /fixtures
  - Rakefile
