categories:
  - Type: Panelist / Committee Member
    Entries:
    - ID: 1
      title: Panelist for the Advanced Scientific Computing Research (ASCR) program of Department of Energy (DOE) funding opportunity - Distributed Resilient Systems.
      year: 2023
      role: DOE ASCR Panelist
    - ID: 2
      title: Panelist for the Advanced Scientific Computing Research (ASCR) program of Department of Energy (DOE) funding opportunity - Management and Storage of Scientific Data 
      year: 2022
      role: DOE ASCR Panelist
    - ID: 3
      title: Program committee member for the 27th edition of the IEEE International Conference on High Performance Computing, Data, and Analytics (HiPC 2020)
      year: 2020
      role: PC Member

  - Type: Invited Paper Reviewer
    Entries:
    - ID: 1
      title: The International Conference for High Performance Computing, Networking, Storage, and Analysis (SC '23)
    - ID: 2
      title: The 52nd International Conference on Parallel Processing (ICPP '23)
    - ID: 3
      title: IEEE International Transactions on Parallel and Distributed Computing Systems (TPDS)
    - ID: 4
      title: IEEE International Parallel and Distributed Processing Symposium (IPDPS)
    - ID: 5
      title: IEEE/ACM International Symposium on Cluster, Cloud and Internet Computing (CCGrid)
    - ID: 6
      title: International Conference on Parallel Processing (ICPP)
    - ID: 7
      title: IEEE International Conference on Cluster Computing (Cluster)
    - ID: 8
      title: IEEE International Conference on Cloud Computing (CLOUD)
    - ID: 9
      title: IEEE International Conference on BigData (BigData)
    - ID: 10
      title: International Conference on Utility and Cloud Computing (UCC)
    - ID: 11
      title: IFIP International Conference on Network and Parallel Computing (NPC)
    - ID: 12
      title: International Parallel Data Systems Workshop (PDSW)
    - ID: 13
      title: International Workshop on Parallel Programming Models and Systems Software for High-End Computing (P2S2)
    - ID: 15
      title: IEEE International Workshop on High-Performance Big Data and Cloud Computing (HPBDC)
    - ID: 16
      title: IEEE Open Access