#!/usr/bin/env bash

set -e

# read first console argument
BASEURL=$1;

echo "Building Jekyll site"

echo "Prepare publication generator"

# install dependencies
cd ./script
python3 -m venv ./
source bin/activate
pip install bibtexparser
pip install pyyaml

echo "Run publication generator"

# generate publication
python publication_generator.py
deactivate
cd ../

# test publications.yml
if test -e "./_data/publications.yml";then
  echo "publications.yml smokes!"
  cat ./_data/publications.yml
else
  echo "Build publications.yml failed"
  exit 1
fi

# lint
bundle exec scss-lint --config=.scss-lint.yml

# test if $BASEURL is non-empty
if [ -z "$BASEURL" ]; then
  bundle exec jekyll build
else
  bundle exec jekyll build --baseurl $BASEURL
fi 


# build Long English version
if test -e "./_site/LResume.html";then
  echo "LResume smokes!"
else
  echo "Build Long EN version failed"
  exit 1
fi

# build Short English version
if test -e "./_site/SResume.html";then
  echo "SResume smokes!"
else
  echo "Build Short EN version failed"
  exit 1
fi

# build Default English version
if test -e "./_site/index.html";then
  echo "index smokes!"
else
  echo "Build Default EN version failed"
  exit 1
fi

# build Chinese version
if test -e "./_site/resume_zh-CN.html";then
  echo "resume_zh-CN smokes!"
else
  echo "Build CN version failed"
  exit 1
fi

# build with Gem
rm -rf ./_site
bundle exec jekyll build --config ./_config_gem.yml
if test -e "./_site/LResume.html";then
  echo "LResume with gem smokes!"
else
  echo "Build Long EN version with Gem failed"
  exit 1
fi
